name := "20-better-webapp"
version := "1.0"
scalaVersion := "2.12.4"
name := "20-better-webapp"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.4"
libraryDependencies += "io.vertx" %% "vertx-web-scala" % "3.5.0"
