name := "09-pattern-matching"
version := "1.0"
scalaVersion := "2.12.4"
name := "09-pattern-matching"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.4"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.4" % "test"
